### ISSUE TITLE
There's no way to "lock" formatting to a given prefix

### ISSUE THREAD

**Issue by TazeTSchnitzel** [ScriptFUSION/ByteFormatter#8]
For example, sometimes it's preferable to format 1500 bytes and 1500000 bytes as 1.5kB and 1,500kB, respectively, instead of 1.5kB and 1.5MB. This is mostly useful when being able to tell large variances at a glance is important (e.g. Windows does this for file sizes in Explorer).

As pointed out on reddit: https://www.reddit.com/r/PHP/comments/3yq3yx/byteformatter_is_a_psr2_compliant_library_that/cygfps8

**Comment by Bilge** [comment]
Is it sufficient to just say, *I want everything to be output using this scale* or is it required to redefine the boundaries at which the scale shifts?

**Comment by TazeTSchnitzel** [comment]
I would assume from their comment that the former is the use case. Though redefining the boundaries might be useful for someone.

**Comment by drrcknlsn** [comment]
I've never come across a situation where I would want to redefine the boundaries, personally, but setting all output to a specific scale is relatively common.  Another example is the `--block-size` flag for `ls`.

**Comment by Bilge** [comment]
@drrcknlsn Out of interest, do you have a real use case for this feature at the moment?

**Comment by Bilge** [comment]
Closed via :bookmark: [3.2.0](https://github.com/ScriptFUSION/ByteFormatter/commit/edc3b7f02b00b460e8139dc019b284e42948612e).
