### ISSUE TITLE
Compatibility for PHP 8.1

### ISSUE THREAD

**Issue by miisieq** [ScriptFUSION/ByteFormatter#9]
Due to the deprecation (https://wiki.php.net/rfc/implicit-float-int-deprecate) merged into PHP 8.1 every time I use **\ScriptFUSION\Byte\ByteFormatter::format** i get the following deprecation message:

`Deprecated: Implicit conversion from float 1.9214055820869274 to int loses precision in /app/vendor/scriptfusion/byte-formatter/src/Byte/ByteFormatter.php on line 63`

**Comment by Bilge** [comment]
Good to know. Do you want to fix it?

**Comment by Bilge** [comment]
Closed via [4.1.0](https://github.com/ScriptFUSION/ByteFormatter/releases/tag/4.1.0).
